import type { GeoSceneKind } from "@/components/GeoScene";

export interface GeographyQuestion {
  id: string;
  type: "continent" | "ocean" | "concept" | "feature" | "climate";
  question: string;
  answer: string;
  choices: string[];
  hint?: string;
  visual?: GeoSceneKind;
  visualLabel?: string;
  explanation?: string;
  pokemonId?: number;
  pokemonName?: string;
  imageDescription?: string;
}

export const geographyQuestions: GeographyQuestion[] = [
  {
    id: "vis-sahara", type: "continent",
    question: "This is the Sahara Desert. Which continent is it in?",
    answer: "Africa",
    choices: ["Africa", "Asia", "Australia"],
    hint: "The Sahara is a huge hot desert in northern Africa",
    visual: "sahara",
    visualLabel: "Sahara Desert",
    explanation: "Yes, Africa. The Sahara is a huge desert in Africa.",
  },
  {
    id: "vis-amazon", type: "continent",
    question: "This rainforest is the Amazon. Which continent is it in?",
    answer: "South America",
    choices: ["South America", "Europe", "Antarctica"],
    hint: "Brazil has a lot of the Amazon rainforest",
    visual: "rainforest",
    visualLabel: "Amazon Rainforest",
    explanation: "Yes, South America. The Amazon rainforest is mostly in South America.",
  },
  {
    id: "vis-antarctica", type: "continent",
    question: "This icy place is Antarctica. Which continent is covered in ice?",
    answer: "Antarctica",
    choices: ["Africa", "Antarctica", "North America"],
    hint: "It is the coldest continent",
    visual: "antarctica",
    visualLabel: "Antarctica",
    explanation: "Yes, Antarctica. It is a cold continent covered with ice.",
  },
  {
    id: "vis-reef", type: "continent",
    question: "The Great Barrier Reef is near which continent?",
    answer: "Australia",
    choices: ["Australia", "Europe", "Africa"],
    hint: "Kangaroos live on this continent too",
    visual: "reef",
    visualLabel: "Great Barrier Reef",
    explanation: "Yes, Australia. The Great Barrier Reef is near Australia.",
  },
  {
    id: "vis-equator", type: "concept",
    question: "Where is the equator on Earth?",
    answer: "Middle",
    choices: ["Top", "Middle", "Bottom"],
    hint: "It is an imaginary line around the middle of Earth",
    visual: "globe-equator",
    visualLabel: "Equator on Earth",
    explanation: "Yes, the equator goes around the middle of Earth.",
  },
  {
    id: "clim-desert", type: "climate",
    question: "What kind of climate is very dry with very little rain?",
    answer: "Desert",
    choices: ["Rainforest", "Desert", "Ocean"],
    hint: "The Sahara is this kind of place",
    visual: "desert",
    visualLabel: "Dry Desert Climate",
    explanation: "Yes, a desert is very dry and gets little rain.",
  },
  {
    id: "clim-rainforest", type: "climate",
    question: "What kind of climate is warm, wet, and full of trees?",
    answer: "Rainforest",
    choices: ["Rainforest", "Ice", "Desert"],
    hint: "Lots of rain helps plants grow here",
    visual: "rainforest",
    visualLabel: "Warm Wet Rainforest",
    explanation: "Yes, rainforests are warm, wet places with many plants.",
  },
  {
    id: "con01", type: "continent",
    question: "On which continent do you find the Sahara Desert and lions?",
    answer: "Africa",
    choices: ["Asia", "Africa", "Europe"],
    hint: "It is the second largest continent",
    visual: "sahara",
    visualLabel: "Sahara Desert",
    explanation: "Africa has the Sahara Desert and many savannas where lions live.",
  },
  {
    id: "con02", type: "continent",
    question: "Which continent is the LARGEST in the world?",
    answer: "Asia",
    choices: ["Asia", "Africa", "North America"],
    hint: "China and India are here",
  },
  {
    id: "con03", type: "continent",
    question: "Which continent is covered in ice and snow, and penguins live there?",
    answer: "Antarctica",
    choices: ["Antarctica", "Australia", "Europe"],
    hint: "It is the coldest place on Earth",
    visual: "antarctica",
    visualLabel: "Icy Antarctica",
    explanation: "Antarctica is the cold continent at the bottom of Earth.",
  },
  {
    id: "con04", type: "continent",
    question: "Which continent has the Amazon rainforest and jaguars?",
    answer: "South America",
    choices: ["North America", "South America", "Africa"],
    hint: "Brazil is here",
    visual: "rainforest",
    visualLabel: "Amazon Rainforest",
    explanation: "The Amazon rainforest grows across South America.",
  },
  {
    id: "con05", type: "continent",
    question: "Which continent has kangaroos and the Great Barrier Reef?",
    answer: "Australia",
    choices: ["Australia", "Asia", "Africa"],
    hint: "It is also an island!",
    visual: "reef",
    visualLabel: "Great Barrier Reef",
    explanation: "Australia is the continent near the Great Barrier Reef.",
  },
  {
    id: "con06", type: "continent",
    question: "Which continent do YOU live on? (USA is part of this continent)",
    answer: "North America",
    choices: ["South America", "North America", "Europe"],
    hint: "Canada, USA, and Mexico are here",
  },
  {
    id: "oc01", type: "ocean",
    question: "What is the LARGEST ocean in the world?",
    answer: "Pacific Ocean",
    choices: ["Atlantic Ocean", "Pacific Ocean", "Indian Ocean"],
    hint: "It covers more than half of Earth's water",
    visual: "ocean",
    visualLabel: "Big Ocean",
    explanation: "The Pacific Ocean is Earth's biggest ocean.",
  },
  {
    id: "oc02", type: "ocean",
    question: "Which ocean is between North America and Europe?",
    answer: "Atlantic Ocean",
    choices: ["Atlantic Ocean", "Pacific Ocean", "Arctic Ocean"],
    hint: "Ships cross this ocean to reach Europe",
  },
  {
    id: "oc03", type: "ocean",
    question: "Which ocean is at the very top of the Earth, near the North Pole?",
    answer: "Arctic Ocean",
    choices: ["Arctic Ocean", "Indian Ocean", "Atlantic Ocean"],
    hint: "It is mostly frozen ice",
  },
  {
    id: "ft01", type: "feature",
    question: "What do we call a very tall rocky landform that touches the clouds?",
    answer: "Mountain",
    choices: ["Mountain", "Island", "Ocean"],
    hint: "Everest is the tallest one",
    visual: "mountain",
    visualLabel: "Tall Mountain",
    explanation: "A mountain is tall, rocky land that rises high.",
  },
  {
    id: "ft02", type: "feature",
    question: "What is a piece of land surrounded by water on all sides?",
    answer: "Island",
    choices: ["Peninsula", "Island", "Mountain"],
    hint: "Hawaii is one!",
  },
  {
    id: "ft03", type: "feature",
    question: "What do we call a very large, dry area with lots of sand and very little rain?",
    answer: "Desert",
    choices: ["Forest", "Desert", "Ocean"],
    hint: "The Sahara is the biggest one",
    visual: "desert",
    visualLabel: "Dry Desert",
    explanation: "A desert is dry and gets very little rain.",
  },
  {
    id: "ft04", type: "feature",
    question: "What do we call an area full of tall trees and lots of animals?",
    answer: "Forest",
    choices: ["Desert", "Ocean", "Forest"],
    hint: "The Amazon is a famous one",
    visual: "forest",
    visualLabel: "Green Forest",
    explanation: "A forest is full of trees and animals.",
  },
  {
    id: "dir01", type: "concept",
    question: "When you face the sunrise, which direction are you looking?",
    answer: "East",
    choices: ["West", "East", "North"],
    hint: "The sun rises in the morning here",
  },
  {
    id: "dir02", type: "concept",
    question: "Which direction does the sun go DOWN (set)?",
    answer: "West",
    choices: ["East", "South", "West"],
    hint: "The sun sets in the evening here",
  },
  {
    id: "dir03", type: "concept",
    question: "Where is the NORTH POLE — at the top or bottom of the Earth?",
    answer: "Top",
    choices: ["Top", "Bottom", "Middle"],
    hint: "Santa Claus lives near here!",
  },
  {
    id: "hot01", type: "concept",
    question: "Which place is HOT all year round?",
    answer: "Near the Equator",
    choices: ["Near the North Pole", "Near the Equator", "On a Mountain Top"],
    hint: "Countries like Brazil and Kenya are here",
    visual: "globe-equator",
    visualLabel: "Equator on Earth",
    explanation: "Places near the equator get strong sunshine and are often warm.",
  },
  {
    id: "hot02", type: "concept",
    question: "Which place is COLD all year round?",
    answer: "Near the North Pole",
    choices: ["Near the Equator", "Near the North Pole", "In a Desert"],
    hint: "Polar bears live here",
    visual: "north-pole",
    visualLabel: "Cold North Pole",
    explanation: "Places near the North Pole are cold for much of the year.",
    pokemonId: 87, pokemonName: "Dewgong",
  },
];
