export interface SpanishQuestion {
  id: string;
  type: "color" | "number" | "greeting" | "phrase";
  question: string;
  spanishWord?: string;
  pokemonId?: number;
  pokemonName?: string;
  answer: string;
  choices: string[];
  hint?: string;
}

export const spanishQuestions: SpanishQuestion[] = [
  {
    id: "col01", type: "color",
    question: "Which Pokemon is ROJO (red)?",
    spanishWord: "rojo",
    pokemonId: 4, pokemonName: "Charmander",
    answer: "Charmander",
    choices: ["Squirtle", "Charmander", "Bulbasaur"],
    hint: "Rojo means RED",
  },
  {
    id: "col02", type: "color",
    question: "Which Pokemon is AZUL (blue)?",
    spanishWord: "azul",
    pokemonId: 7, pokemonName: "Squirtle",
    answer: "Squirtle",
    choices: ["Squirtle", "Pikachu", "Eevee"],
    hint: "Azul means BLUE",
  },
  {
    id: "col03", type: "color",
    question: "Which Pokemon is AMARILLO (yellow)?",
    spanishWord: "amarillo",
    pokemonId: 25, pokemonName: "Pikachu",
    answer: "Pikachu",
    choices: ["Charmander", "Pikachu", "Bulbasaur"],
    hint: "Amarillo means YELLOW",
  },
  {
    id: "col04", type: "color",
    question: "Which Pokemon is VERDE (green)?",
    spanishWord: "verde",
    pokemonId: 1, pokemonName: "Bulbasaur",
    answer: "Bulbasaur",
    choices: ["Bulbasaur", "Pikachu", "Meowth"],
    hint: "Verde means GREEN",
  },
  {
    id: "col05", type: "color",
    question: "Which Pokemon is ROSA (pink)?",
    spanishWord: "rosa",
    pokemonId: 39, pokemonName: "Jigglypuff",
    answer: "Jigglypuff",
    choices: ["Jigglypuff", "Squirtle", "Charmander"],
    hint: "Rosa means PINK",
  },
  {
    id: "num01", type: "number",
    question: "What is UNO?",
    spanishWord: "uno",
    answer: "1",
    choices: ["1", "2", "3"],
    hint: "Uno = 1",
  },
  {
    id: "num02", type: "number",
    question: "What is DOS?",
    spanishWord: "dos",
    answer: "2",
    choices: ["1", "2", "3"],
    hint: "Dos = 2",
  },
  {
    id: "num03", type: "number",
    question: "What is TRES?",
    spanishWord: "tres",
    answer: "3",
    choices: ["2", "3", "4"],
    hint: "Tres = 3",
  },
  {
    id: "num04", type: "number",
    question: "What is CUATRO?",
    spanishWord: "cuatro",
    answer: "4",
    choices: ["3", "4", "5"],
    hint: "Cuatro = 4",
  },
  {
    id: "num05", type: "number",
    question: "What is CINCO?",
    spanishWord: "cinco",
    answer: "5",
    choices: ["4", "5", "6"],
    hint: "Cinco = 5",
  },
  {
    id: "num06", type: "number",
    question: "¿Cuántos Pikachu? How many Pikachu?",
    spanishWord: "cuántos",
    pokemonId: 25, pokemonName: "Pikachu",
    answer: "tres",
    choices: ["uno", "dos", "tres"],
    hint: "Count the Pikachu!",
  },
  {
    id: "gr01", type: "greeting",
    question: "How do you say HELLO in Spanish?",
    answer: "Hola",
    choices: ["Adios", "Hola", "Gracias"],
    hint: "It starts with H",
  },
  {
    id: "gr02", type: "greeting",
    question: "How do you say GOODBYE in Spanish?",
    answer: "Adios",
    choices: ["Hola", "Adios", "Por favor"],
    hint: "It starts with A",
  },
  {
    id: "gr03", type: "greeting",
    question: "How do you say THANK YOU in Spanish?",
    answer: "Gracias",
    choices: ["Gracias", "Hola", "Si"],
    hint: "It starts with G",
  },
  {
    id: "gr04", type: "greeting",
    question: "How do you say PLEASE in Spanish?",
    answer: "Por favor",
    choices: ["Gracias", "Hola", "Por favor"],
    hint: "It means 'for favor'",
  },
  {
    id: "ph01", type: "phrase",
    question: "What does BUENOS DIAS mean?",
    spanishWord: "buenos dias",
    answer: "Good morning",
    choices: ["Good night", "Good morning", "Good afternoon"],
    hint: "Dias = days",
  },
  {
    id: "ph02", type: "phrase",
    question: "What does ME LLAMO mean?",
    spanishWord: "me llamo",
    answer: "My name is",
    choices: ["I am happy", "My name is", "I like it"],
    hint: "You say this to introduce yourself",
  },
  {
    id: "col06", type: "color",
    question: "Which Pokemon is NARANJA (orange)?",
    spanishWord: "naranja",
    pokemonId: 6, pokemonName: "Charizard",
    answer: "Charizard",
    choices: ["Charizard", "Squirtle", "Bulbasaur"],
    hint: "Naranja means ORANGE",
  },
  {
    id: "col07", type: "color",
    question: "Which Pokemon is MORADO (purple)?",
    spanishWord: "morado",
    pokemonId: 94, pokemonName: "Gengar",
    answer: "Gengar",
    choices: ["Gengar", "Pikachu", "Charmander"],
    hint: "Morado means PURPLE",
  },
  {
    id: "col08", type: "color",
    question: "Which Pokemon is NEGRO (black)?",
    spanishWord: "negro",
    pokemonId: 197, pokemonName: "Umbreon",
    answer: "Umbreon",
    choices: ["Umbreon", "Pikachu", "Squirtle"],
    hint: "Negro means BLACK",
  },
  {
    id: "col09", type: "color",
    question: "Which Pokemon is MARRON (brown)?",
    spanishWord: "marrón",
    pokemonId: 133, pokemonName: "Eevee",
    answer: "Eevee",
    choices: ["Eevee", "Squirtle", "Bulbasaur"],
    hint: "Marrón means BROWN",
  },
  {
    id: "num07", type: "number",
    question: "What is SEIS?",
    spanishWord: "seis",
    answer: "6",
    choices: ["5", "6", "7"],
    hint: "Seis = 6",
  },
  {
    id: "num08", type: "number",
    question: "What is SIETE?",
    spanishWord: "siete",
    answer: "7",
    choices: ["6", "7", "8"],
    hint: "Siete = 7",
  },
  {
    id: "num09", type: "number",
    question: "What is OCHO?",
    spanishWord: "ocho",
    answer: "8",
    choices: ["7", "8", "9"],
    hint: "Ocho = 8",
  },
  {
    id: "num10", type: "number",
    question: "What is NUEVE?",
    spanishWord: "nueve",
    answer: "9",
    choices: ["8", "9", "10"],
    hint: "Nueve = 9",
  },
  {
    id: "num11", type: "number",
    question: "What is DIEZ?",
    spanishWord: "diez",
    answer: "10",
    choices: ["9", "10", "11"],
    hint: "Diez = 10",
  },
  {
    id: "gr05", type: "greeting",
    question: "How do you say GOOD NIGHT in Spanish?",
    spanishWord: "buenas noches",
    answer: "Buenas noches",
    choices: ["Buenos dias", "Buenas noches", "Hola"],
    hint: "Noches = nights",
  },
  {
    id: "gr06", type: "greeting",
    question: "How do you say YOU'RE WELCOME in Spanish?",
    spanishWord: "de nada",
    answer: "De nada",
    choices: ["De nada", "Gracias", "Adios"],
    hint: "You say it after 'gracias'",
  },
  {
    id: "gr07", type: "greeting",
    question: "How do you say YES in Spanish?",
    spanishWord: "sí",
    answer: "Si",
    choices: ["Si", "No", "Hola"],
    hint: "It sounds like 'see'",
  },
  {
    id: "gr08", type: "greeting",
    question: "How do you say NO in Spanish?",
    spanishWord: "no",
    answer: "No",
    choices: ["Si", "No", "Gracias"],
    hint: "It's the same word!",
  },
  {
    id: "ph03", type: "phrase",
    question: "What does COMO ESTAS mean?",
    spanishWord: "¿cómo estás?",
    answer: "How are you?",
    choices: ["What is your name?", "How are you?", "Where are you?"],
    hint: "You ask this to a friend",
  },
  {
    id: "ph04", type: "phrase",
    question: "What does MUY BIEN mean?",
    spanishWord: "muy bien",
    answer: "Very good",
    choices: ["Very good", "Very big", "Good night"],
    hint: "Bien = good",
  },
  {
    id: "ph05", type: "phrase",
    question: "What does MUCHO GUSTO mean?",
    spanishWord: "mucho gusto",
    answer: "Nice to meet you",
    choices: ["See you later", "Nice to meet you", "Thank you"],
    hint: "You say it when you meet someone",
  },
  {
    id: "ph06", type: "phrase",
    question: "What does TENGO CINCO ANOS mean?",
    spanishWord: "tengo cinco años",
    answer: "I am five years old",
    choices: ["I am five years old", "I have five toys", "I want five"],
    hint: "Años = years",
  },
];
